server:
  port: 8081
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2word
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

# Swagger json url address
# etc. https://petstore.swagger.io/
# swagger.url: https://petstore.swagger.io/v2/swagger.json
# 配置需要导出的swagger接口模块地址
swagger.url: http://192.168.2.121:8082/v2/api-docs?group=档案管理模块接口







